### ISSUE TITLE
Instagram Directe Messages

### ISSUE THREAD

**Issue by chrisspiegl** [kan/franz-plugin-instagram#1]
Thanks for this integration. Looking good for some Instagram in Franz. Is it possible to get the Direct Messaging in Instagram Working directly as a plugin? Do you know? Could you do it?

Thanks again 👍

**Comment by kan** [comment]
Thank you for choosing this plugin.

It is technically possible to check receipt of instagram's direct message. Since I do not use direct messages so much, I was going to postpone it, but I think I will try to implement it. Please wait patiently ☺️

**Comment by chrisspiegl** [comment]
That sounds great - I'll wait patiently. And am looking forward to it :)

**Comment by kan** [comment]
@spieglio I fix this problem 749139b . Please try it.

**Comment by chrisspiegl** [comment]
Hey @kan - interesting. It now shows the number of unread DirectMessages. But I am not able to find a way to see the direct messages? Is there something I am missing?

**Comment by kan** [comment]
I had never actually received DirectMessage, so I thought that DM would be displayed on the upper left pull-down menu (which is the menu that pushes the heart icon and exits) as well as comments and "like" Current Instagram does not seem to support DM browsing on PC (web) 😭

**Comment by chrisspiegl** [comment]
Apparently they don't :( sorry. You can try sending me a message on IG.

https://instagram.com/spieglio

So we can test it 👍

**Comment by kan** [comment]
Thank you. Thanks to you I have tested the direct message.
However, it is still impossible to see the direct message on the PC, and it seems that it is not notified 😢

**Comment by chrisspiegl** [comment]
Thanks for trying. Seems like Instagram does not support web chat (yet). Hopefully they will in the future at some point.

**Comment by gsonnet911** [comment]
Hey, there is an instagram windows store app from which it is possible to direct message. I would be very grateful  if someone managed to find a way to integrate this into Franz (no clue if its possible, but the thought is nice).

**Comment by kan** [comment]
I tried to examine, Instagram's Windows application seems to be made natively, it seems that it can not be handled from Franz which is a web browser. I'm sorry I could not become a force.

**Comment by gsonnet911** [comment]
No problem, thank you for your feedback!

Best,

Gaby

**Comment by ghost** [comment]
Hi! When I try to install this, it logs me out and will still not show me instagram as an option for adding an application. It will also not allow me to choose any other apps to install. 
Any suggestions?

**Comment by kan** [comment]
Thank you for using this plugin.
I already have not used Franz and it is difficult to support plugins. sorry

**Comment by naoliden** [comment]
I'm waiting for DM integration to start using Franz. It'd be the best if you could manage to do so. It'd solve so many problems for me 👍
